### ISSUE TITLE
Blight Resisntance Relic fragment's numbers, not being reflected

### ISSUE THREAD

**Issue by matchet23** [joshpayette/remnant2-toolkit#182]
Pick a build which haves this relic fragment, i.e: 
https://www.remnant2toolkit.com/builder/clwa4785f004xbah28edop3rs 

Note that Blight Resistance numbers on this build arent changed. 
Ingame, there is a typo on the description for it says it increases Blight Resistances by 30 percent, but it does increases resistances by plain +30. 
In my game, it states I do have 43 points in Blight resistance with that relic fragment on my relic.

**Comment by joshpayette** [comment]
Thank you for letting me know! I will take a look this evening to see why it isn't tallying correctly.

Regarding the ingame stating 30 percent, that's actually not a typo. It's kind of poorly worded where each point is 1 percent, rather than an item increasing the value by 30 percent of the current value

**Comment by joshpayette** [comment]
Turns out the relic fragment did not have blight resistance specified under the hood. This has been fixed and is deploying now. Thank you for taking the time to submit this report and help improve the Toolkit!
