### ISSUE TITLE
Replace 'Relicfragment' with 'Relic Fragment'

### ISSUE THREAD

**Issue by AlexijSeptimus** [joshpayette/remnant2-toolkit#43]
For consistency and readability.

**Comment by joshpayette** [comment]
This is going to be a bit of a bigger update, similar to the archetype fix, since the keys for many objects reference `relicfragment`. It's doable and I think it's a good idea, but will require a bunch of testing to make sure I don't break anything!

**Comment by joshpayette** [comment]
I believe I have fixed all of this. Instead of changing everything under the hood, which would cause potentially more issues, I tried to identify every UI element that displays the item category to read 'relic fragment' where applicable. If I missed any specific instances, please let me know where it is wrong and I will update it!

Thank you!

**Comment by AlexijSeptimus** [comment]
Good hack! Looks good.
